# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[override]]
  branch = "master"
  name = "github.com/katzenpost/core"

[[override]]
  branch = "master"
  name = "github.com/katzenpost/minclient"

[[override]]
  branch = "reply_bookkeeping.1"
  name = "github.com/katzenpost/client"

[[constraint]]
  branch = "master"
  name = "github.com/katzenpost/authority"

[[constraint]]
  branch = "master"
  name = "github.com/katzenpost/mailproxy"

[[constraint]]
  branch = "kaetzchen_plugin_system.0.add_parameters.1"
  name = "github.com/katzenpost/server"

[[constraint]]
  version = "1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"
