
# bbolt is a transitive dependency, and go dep favors v1.3.0, which is
# lacking `Bucket.SetSequence()`.
required = ["github.com/coreos/bbolt"]

[[constraint]]
  version = "1.3.1-coreos.6"
  name = "github.com/coreos/bbolt"

[[override]]
  name = "github.com/katzenpost/core"
  branch = "voting_release"

[[override]]
  name = "github.com/katzenpost/authority"
  branch = "voting_release"

[[override]]
  version = "v0.0.2"
  name = "github.com/katzenpost/minclient"

[[override]]
  name = "github.com/katzenpost/mailproxy"
  branch = "voting_release"

[[override]]
  branch = "master"
  name = "github.com/katzenpost/panda"

[[override]]
  name = "github.com/katzenpost/playground"
  version = "0.0.2"

[[override]]
  branch = "master"
  name = "github.com/katzenpost/registration_client"

[[override]]
  name = "github.com/katzenpost/server"
  branch = "voting_release"

# other stuff

[[override]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[override]]
  name = "github.com/abiosoft/ishell"
  version = "2.0.0"

[[override]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[override]]
  branch = "master"
  name = "github.com/hpcloud/tail"


[[override]]
  name = "github.com/ugorji/go"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true
